### ISSUE TITLE
[FEATURE] Auto Re-Position

### ISSUE THREAD

**Issue by sfksuperman** [Khiro95/Awqat-Salaat#24] opened 2024-07-08 12:55 UTC
Is it possible to auto re-position every 1 min for like 5 mins (5 times) as soon as the windows start, and/or re-position automatically as soon as the current position changes which triggers the re-positioning?

**Comment by Khiro95** [comment] 2024-07-08 13:38
> Is it possible to auto re-position every 1 min for like 5 mins (5 times) as soon as the windows start

Hi @sfksuperman, yes it's possible. But why do that every 1 min for 5 min? why not do it every 1 min for the whole execution time?

> and/or re-position automatically as soon as the current position changes which triggers the re-positioning?

Sorry, I don't get what you mean

**Comment by sfksuperman** [comment] 2024-07-08 14:36
Forget about every 1 minute for like 5 minutes. Let's focus on the second thing. What I mean is after pc boots, a few minutes/hours later, due to the network monitor continuous speed live showing, sometimes the position of the AS app overlaps with the NM app.

So, I want the app to monitor the initial position after a perfect re-position on the taskbar and remember the position and as soon as after x mins/hours the position is changed, the re-position function triggers and fixes the AS widget position on the taskbar. This should be automatic. So no more manual re-positioning.

**Comment by Khiro95** [comment] 2024-07-08 17:29
Hi @sfksuperman 

What is this NM app? If it's **Traffic Monitor**, then I suggest you open a [new issue](https://github.com/zhongyang219/TrafficMonitor/issues) asking them to make the taskbar widget's width fixed.

Don't get me wrong, but that's an issue caused by an external app so I'm not sure why we have to implement a *workaround* for a third party tool that is not even used by our widget.

I'm not saying that your suggestion isn't applicable, but let's first try the correct solution. If that fails, then we look for workarounds.

Also since I'm planing to implement manual positioning at a fixed offset, would this work for you or you think a periodic auto-reposition is needed?

**Comment by Khiro95** [comment] 2024-09-06 13:50
Hi @sfksuperman

Manual position is now implemented for the next release.

![drag_awqat_2](https://github.com/user-attachments/assets/2f900db2-28d0-4f22-b218-f0a52b622df2)

Do you think this feature will solve your issue or it need more improvements?

**Comment by sfksuperman** [comment] 2024-09-07 09:18
Thanks bro, this is good but will the position be fixed when I use Manual Position? Or it will again shift to left/right on its own?

**Comment by Khiro95** [comment] 2024-09-07 10:48
> Thanks bro, this is good but will the position be fixed when I use Manual Position? Or it will again shift to left/right on its own?

You are welcome @sfksuperman 

The position will be fixed until you click on **Re-position** again :)

**Comment by sfksuperman** [comment] 2024-09-07 14:36
That's cool. Thanks a lot.

**Closed** 2024-10-03 13:31 UTC
Labels: enhancement
