### ISSUE TITLE
Failed startup after changing regional format

### ISSUE THREAD

**Issue by mihi130721** [Khiro95/Awqat-Salaat#35] opened 2024-10-09 02:11 UTC
Installed Awqat-Salaat on Win11 laptop via the Microsoft Store. Installed and worked fine, However, at the time, had 'Co-Pilot', 'Task View', 'Widgets' and 'Chat' enabled. Disabled these. The app was still working, and was positioned correctly in the taskbar. However, on restart, the attached error came up.
![Screenshot 2024-10-09 025541](https://github.com/user-attachments/assets/a633cdcd-3a08-42b1-b8da-304d4eb74e98)

Tried re-installing, tried deleting app data etc. If widgets is disabled, it says that the taskbar is unavailable, so tried with just widgets enabled, but still received same error.

Am happy to lend assistance in testing any bug fix, please message.

**Comment by Khiro95** [comment] 2024-10-09 11:01
Salam @mihi130721 

Thank you for reporting this problem!

I would like to know few things here to understand the error message:
- What is the resolution/size of your screen?
- Are you using multi screen?
- Is your OS in Arabic? I think it is, but I want to be sure :)

Also I'm not sure I understood correctly, but are you saying that re-installing the widget doesn't fix the problem?

For "the taskbar is unavailable" message, it means that there is some menu/panel open from the taskbar (e.g. the Start menu, notification center panel, system tray menu for hidden icons, context-menu opened from the taskbar, ... etc).

Once again, thanks for the feedback, I've been looking for some since the release of the widget on the store which sadly is crashing a lot currently and I have no idea why because it works fine for me. Any information is highly appreciated.

**Comment by Sheikhm007** [comment] 2024-10-09 15:06
I have been using the Microsoft Store app from the day you released it and
it is working fine without any issues. Thanks for making this app so good !
Just add the Athan feature soon :)

**Comment by mihi130721** [comment] 2024-10-10 07:32
> Salam @mihi130721
> 
> Thank you for reporting this problem!
> 
> I would like to know few things here to understand the error message:
> 
>     * What is the resolution/size of your screen?
> 
>     * Are you using multi screen?
> 
>     * Is your OS in Arabic? I think it is, but I want to be sure :)
> 
> 
> Also I'm not sure I understood correctly, but are you saying that re-installing the widget doesn't fix the problem?
> 
> For "the taskbar is unavailable" message, it means that there is some menu/panel open from the taskbar (e.g. the Start menu, notification center panel, system tray menu for hidden icons, context-menu opened from the taskbar, ... etc).
> 
> Once again, thanks for the feedback, I've been looking for some since the release of the widget on the store which sadly is crashing a lot currently and I have no idea why because it works fine for me. Any information is highly appreciated.

Wa Alaykum Salam Khiro,

- Resolution is 1920x1080, 15.6 inch 16:9 screen.
- Not using multi-screen
- My OS is in English however...

In order to display the Hijri date, I installed a Windows Arabic language pack and set the system date-time to use Arabic (Saudi Arabia), I then ammended some values to allow the Hijri date to display.

![image](https://github.com/user-attachments/assets/c9773b17-641a-4374-be48-fbe950722c76)

I did this after I installed Awqat and this changed occured before I saw the error, but I presumed it had nothing to do with the error, but instead my fidgeting with the widgets did. However, since you messaged, I am having issues with Awqat on my main desktop too (will post details below) - and the only change I have made on that recently is also changing the system date-time to Arabic to allow the Hijri date to display. So I am now thinking it has something to do with this?

**Comment by mihi130721** [comment] 2024-10-10 07:34
![image](https://github.com/user-attachments/assets/4fdd0131-79b7-49f5-bd2f-88af0064d9a5)

For where above mentioned change was made.

**Comment by Khiro95** [comment] 2024-10-10 12:09
@mihi130721 Thanks for the detailed answer about these changes!
I can reproduce this behavior now
![image](https://github.com/user-attachments/assets/adaedb65-1b76-473f-b16a-e4173181ab50)

So changing the regional format settings make the widget detect the wrong system language.

I apologize for the inconvenience, but you may need to revert your changes for now to be able to use the widget until the next update :(

If I can find what's making the widget crashing for other people, I will release a patch ASAP including the fix for this bug.

**Comment by Khiro95** [comment] 2024-10-10 19:19
@mihi130721 It seems like more people are affected by this bug, so I will release a patch to fix this critical issue. It should be available tomorrow insha'Allah.

**Closed** 2024-10-10 20:30 UTC
Labels: bug
